# C++ is a fully OOPS language
'''class avengers:
    a1="Captain"
    a2="Iron Man"
    a3="Thor"
    a4="Black widow"
    a5="Black Panther"
    a6="Spider Man"
    def infinitywar(self):
        print("50% of the people are vanished")
civilwar=avengers()
print(civilwar.a1)
print(civilwar.a2)
print(civilwar.a3)
print(civilwar.a4)


# Movies
class movies_mine:
    def telugu(self):
        print("RRR is the oscar winning movie in the telugu\n")
    def hindi(self):
        print("Jawan is the bestt movie ever watched\n")
    def kannada(self):
        print("Kannada movies are boring\n")  

vaish=movies_mine()         
print(vaish.telugu()) 
vaish=movies_mine()         
print(vaish.hindi()) 
vaish=movies_mine()         
print(vaish.kannada()) '''

# Movie ticket generator
class movie:
  n=str(input())
  tc=int(input())
  mob=str(input())
m1=movie() 
m2=movie()
m1.n
m1.tc
m1.mob
print(m1.n)
print(m1.tc)
print(m1.mob)








































# Class is a collection of various functions attributes and objects
# Object is a denotation of any particular class 
# Attributes are the characteristics or properties that an object has
# Methods are the actions performed by an object